第5阶段web框架之Django/day60CBV/bookmananger/bookmananger/urls.py
from django.conf.urls import url
from django.contrib import admin

from app01 import views

urlpatterns = [
    # 系统管理
    url(r'^admin/', admin.site.urls),
    # 展示出版社
    url(r'^publisher_list/', views.ListPublisher.as_view()),
    # 添加出版社
    url(r'^publisher_add/', views.AddPublisher.as_view()),
    # 删除出版社
    url(r'^publisher_del/', views.DelPublisher.as_view()),
    # 编辑出版社
    url(r'^publisher_edit/', views.EditPublisher.as_view()),
    # 展示书籍
    url(r'^book_list/', views.ListBook.as_view()),
    # 添加书籍
    url(r'^book_add/', views.AddBook.as_view()),
    # 删除书籍
    url(r'^book_del/', views.DelBook.as_view()),
    # 编辑书籍
    url(r'^book_edit/', views.EditBook.as_view()),
    # 展示作者
    url(r'^author_list/', views.ListAuthor.as_view()),
    # 添加作者
    url(r'^author_add/', views.AddAuthor.as_view()),
    # 删除作者
    url(r'^author_del/', views.DelAuthor.as_view()),
    # 编辑作者
    url(r'^author_edit/', views.EditAuthor.as_view()),
]

第5阶段web框架之Django/day60CBV/bookmananger/app01/models.py
from django.db import models


class Publisher(models.Model):
    pid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return "{} {}".format(self.pid, self.name)

    __repr__ = __str__


class Book(models.Model):
    title = models.CharField(max_length=32)
    pub = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    # authors = models.ManyToManyField('Author')  # 描述多对多的关系   不生成字段  生成关系表

    def __repr__(self):
        return self.title

    __str__ = __repr__

class Author(models.Model):
    name = models.CharField(max_length=32)
    books = models.ManyToManyField('Book')  # 描述多对多的关系   不生成字段  生成关系表

第5阶段web框架之Django/day60CBV/bookmananger/app02/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=32)


class Author(models.Model):
    name = models.CharField(max_length=32)
    books = models.ManyToManyField(Book, through='Book_Author', through_fields=['author', 'book', ])


class Book_Author(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='x')
    tuijian_author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='x1')
    date = models.DateField()

第5阶段web框架之Django/day60CBV/bookmananger/app01/views.py
from django.shortcuts import render, HttpResponse, redirect
from app01 import models
from django.views import View
from django.utils.decorators import method_decorator
import time


def timer(func):
    def inner(*args, **kwargs):
        start = time.time()
        ret = func(*args, **kwargs)
        print("{}".format(time.time() - start))
        return ret

    return inner


class ListPublisher(View):
    @method_decorator(timer)
    def get(self, request):
        # 从数据库中查询出所有的出版社
        all_publishers = models.Publisher.objects.all().order_by('pid')
        # 返回一个页面  页面包含数据
        return render(request, 'publisher_list.html', {'all_publishers': all_publishers})


# 新增出版社
class AddPublisher(View):
    http_method_names = ['get']

    @method_decorator(timer)
    def dispatch(self, request, *args, **kwargs):
        ret = super().dispatch(request, *args, **kwargs)
        return ret

    def get(self, request):
        return render(request, 'publisher_add.html')

    def post(self, request):
        pub_name = request.POST.get('pub_name')
        if not pub_name:
            # 输入为空
            error = '输入不能为空'
        elif models.Publisher.objects.filter(name=pub_name):
            # 数据库已存在该数据
            error = '数据已存在'
        else:
            # 插入数据
            models.Publisher.objects.create(name=pub_name)
            # 跳转至展示页面
            return redirect('/publisher_list/')

        return render(request, 'publisher_add.html', {'pub_name': pub_name, 'error': error})


# 删除出版社

class DelPublisher(View):
    def get(self, request):
        pk = request.GET.get('pk')

        query = models.Publisher.objects.filter(pk=pk)  # 对象列表
        if not query:
            # 数据部存在
            return HttpResponse('要删除的数据不存在')
        # 删除数据
        query.delete()  # 通过queryset 删除
        # query[0].delete()  # 通过单独的对象 删除
        # 跳转至展示页面
        return redirect('/publisher_list/')


# 编辑出版社
@method_decorator(timer,name="get")
@method_decorator(timer,name='post')
@method_decorator(timer,name='dispatch')
class EditPublisher(View):
    def get(self, request):
        pk = request.GET.get('pk')  # url上携带的参数
        obj = models.Publisher.objects.filter(pk=pk).first()
        if not obj:
            return HttpResponse('要编辑的对象不存在')
        return render(request, 'publisher_edit.html')

    def post(self, request):
        pk = request.GET.get('pk')  # url上携带的参数
        obj = models.Publisher.objects.filter(pk=pk).first()
        pub_name = request.POST.get('pub_name')
        if not pub_name:
            # 输入为空
            error = '输入不能为空'
        elif models.Publisher.objects.filter(name=pub_name):
            # 数据库已存在该数据
            error = '数据已存在'
        else:
            # 编辑原始的对象
            obj.name = pub_name
            obj.save()
            # 跳转至展示页面
            return redirect('/publisher_list/')
        return render(request, 'publisher_edit.html', {'obj': obj, 'error': error})


# 展示书籍
class ListBook(View):
    def get(self, request):
        all_books = models.Book.objects.all()
        return render(request, 'book_list.html', {'all_books': all_books})


# 添加书籍
class AddBook(View):
    def get(self, request):
        # 查询所有的出版社
        all_publishers = models.Publisher.objects.all()
        return render(request, 'book_add.html', {'all_publishers': all_publishers})

    def post(self, request):
        # 获取提交的数据
        title = request.POST.get('title')
        pub_id = request.POST.get('pub_id')
        # 插入数据库
        # obj = models.Book.objects.create(title=title,pub=models.Publisher.objects.get(pk=pub_id))
        models.Book.objects.create(title=title, pub_id=pub_id)

        # 跳转到展示页面
        return redirect('/book_list/')


# 删除书籍
class DelBook(View):
    def get(self, request):
        pk = request.GET.get('pk')
        models.Book.objects.filter(pk=pk).delete()
        return redirect('/book_list/')


# 编辑书籍
class EditBook(View):
    def get(self, request):
        pk = request.GET.get('pk')
        book_obj = models.Book.objects.filter(pk=pk).first()
        all_publishers = models.Publisher.objects.all()
        return render(request, 'book_edit.html', {'book_obj': book_obj, 'all_publishers': all_publishers})

    def post(self, request):
        pk = request.GET.get('pk')
        book_obj = models.Book.objects.filter(pk=pk).first()
        if request.method == 'POST':
            title = request.POST.get('title')
            pub_id = request.POST.get('pub_id')
            book_obj.title = title
            book_obj.pub_id = pub_id
            book_obj.save()
            return redirect('/book_list/')


# 展示作者
class ListAuthor(View):
    def get(self, request):
        # 查询所有的作者
        all_authors = models.Author.objects.all().order_by('id')
        return render(request, 'author_list.html', {'all_authors': all_authors})


# 添加作者
class AddAuthor(View):
    def get(self, request):
        all_books = models.Book.objects.all()
        return render(request, 'author_add.html', {'all_books': all_books})

    def post(self, request):
        name = request.POST.get('name')
        books = request.POST.getlist('books')
        # 插入数据库
        # 新建作者
        author_obj = models.Author.objects.create(name=name)
        # 给作者和书籍绑定关系
        author_obj.books.set(books)
        # 跳转到展示页面
        return redirect('/author_list/')


# 删除作者
class DelAuthor(View):
    def get(self, request):
        pk = request.GET.get('pk')
        models.Author.objects.filter(pk=pk).delete()
        return redirect('/author_list/')


# 编辑作者
class EditAuthor(View):
    def get(self, request):
        pk = request.GET.get('pk')
        obj = models.Author.objects.filter(pk=pk).first()
        all_books = models.Book.objects.all()
        return render(request, 'author_edit.html', {'obj': obj, 'all_books': all_books})

    def post(self, request):
        name = request.POST.get('name')
        books = request.POST.getlist('books')
        pk = request.GET.get('pk')
        obj = models.Author.objects.filter(pk=pk).first()
        # 修改
        obj.name = name
        obj.save()
        obj.books.set(books)  # 修改作者和书的多对多关系

        # 跳转到展示页面
        return redirect('/author_list/')

第5阶段web框架之Django/day60CBV/bookmananger/app02/views.py
from django.shortcuts import render

# Create your views here.

第5阶段web框架之Django/day60CBV/bookmananger/templates/abase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/dashboard.css">
    <style>

        .table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {

            padding: 8px;
            line-height: 1.42857143;
            vertical-align: middle;
            border-top: 1px solid #ddd;
        }

    </style>
</head>

<body>
{% include 'nav.html' %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                {% block active %}
                {% endblock %}
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <div class="panel panel-primary">
                {%  block zhuti %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>


</body>
</html>

第5阶段web框架之Django/day60CBV/bookmananger/templates/author_add.html
{% extends 'abase.html' %}

{% block active %}
    <li><a href="/book_list/">书籍列表 <span class="sr-only">(current)</span></a></li>
    <li><a href="/publisher_list/">出版社列表 <span class="sr-only">(current)</span></a></li>
    <li class="active"><a href="/author_list/">作者列表 <span class="sr-only">(current)</span></a></li>
{% endblock %}

{% block zhuti %}
    <div class="panel-heading">添加作者</div>
    <div class="panel-body">
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">作者：</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" id="inputEmail3" name="name">
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">著作</label>
                <div class="col-sm-6">
                    <select name="pub_id" class="form-control">
                        {% for book in all_books %}
                            <option value="{{ book.pk }}">{{ book.title }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

第5阶段web框架之Django/day60CBV/bookmananger/templates/author_edit.html
{% extends 'abase.html' %}

{% block active %}
    <li><a href="/book_list/">书籍列表 <span class="sr-only">(current)</span></a></li>
    <li><a href="/publisher_list/">出版社列表 <span class="sr-only">(current)</span></a></li>
    <li class="active"><a href="/author_list/">作者列表 <span class="sr-only">(current)</span></a></li>
{% endblock %}

{% block zhuti %}
    <div class="panel-heading">编辑作者</div>
    <div class="panel-body">
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">作者：</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" id="inputEmail3" name="name"
                           value="{{ obj.name }}">
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">作者</label>
                <div class="col-sm-6">
                    <select name="books" class="form-control" id="" multiple>
                        {% for book in all_books %}
                            {% if book in obj.books.all %}
                                <option selected value="{{ book.pk }}">{{ book.title }}</option>
                            {% else %}
                                <option value="{{ book.pk }}">{{ book.title }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

第5阶段web框架之Django/day60CBV/bookmananger/templates/author_list.html
{% extends 'abase.html' %}

{% block active %}
    <li><a href="/book_list/">书籍列表 <span class="sr-only">(current)</span></a></li>
    <li><a href="/publisher_list/">出版社列表 <span class="sr-only">(current)</span></a></li>
    <li class="active"><a href="/author_list/">作者列表 <span class="sr-only">(current)</span></a></li>
{% endblock %}

{% block zhuti %}
    <div class="panel-heading">作者列表</div>
    <div class="panel-body">
        <a class="btn btn-primary btn-sm" href="/author_add/"> 添加 </a>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>序号</th>
                <th>ID</th>
                <th>作者姓名</th>
                <th>著作</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for author in all_authors %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ author.pk }}</td>
                    <td>{{ author.name }}</td>
                    <td>
                        {% for book in author.books.all %}
                            《{{ book }}》
                        {% endfor %}
                    </td>
                    <td>
                        <a class="btn btn-danger btn-sm" href="/author_del/?pk={{ author.pk }}">删除</a>
                        <a class="btn btn-warning btn-sm" href="/author_edit/?pk={{ author.pk }}">编辑</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

第5阶段web框架之Django/day60CBV/bookmananger/templates/book_add.html
{% extends 'abase.html' %}

{% block active %}
    <li class="active"><a href="/book_list/">书籍列表 <span class="sr-only">(current)</span></a></li>
    <li><a href="/publisher_list/">出版社列表 <span class="sr-only">(current)</span></a></li>
    <li><a href="/author_list/">作者列表 <span class="sr-only">(current)</span></a></li>
{% endblock %}

{% block zhuti %}
    <div class="panel-heading">添加书籍</div>
    <div class="panel-body">
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">书籍名称</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" id="inputEmail3" name="title"
                           value="{{ pub_name }}">
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">出版社</label>
                <div class="col-sm-6">
                    <select name="pub_id" class="form-control">
                        {% for publisher in all_publishers %}
                            <option value="{{ publisher.pk }}"> {{ publisher.name }} </option>
                        {% endfor %}

                    </select>

                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

第5阶段web框架之Django/day60CBV/bookmananger/templates/book_edit.html
{% extends 'abase.html' %}
{% block active %}
    <li class="active"><a href="/book_list/">书籍列表 <span class="sr-only">(current)</span></a></li>
    <li><a href="/publisher_list/">出版社列表 <span class="sr-only">(current)</span></a></li>
    <li><a href="/author_list/">作者列表 <span class="sr-only">(current)</span></a></li>
{% endblock %}

{% block zhuti %}
    <div class="panel-heading">编辑书籍</div>
    <div class="panel-body">
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <div class="form-group">

                <label for="inputEmail3" class="col-sm-3 control-label">书籍名称</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" id="inputEmail3" name="title"
                           value="{{ book_obj.title }}">
                </div>

            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">出版社</label>
                <div class="col-sm-6">

                    <select name="pub_id" class="form-control">
                        {% for publisher in all_publishers %}
                            {% if book_obj.pub == publisher %}
                                <option selected value="{{ publisher.pk }}"> {{ publisher.name }} </option>
                            {% else %}
                                <option value="{{ publisher.pk }}"> {{ publisher.name }} </option>
                            {% endif %}
                        {% endfor %}
                    </select>

                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

第5阶段web框架之Django/day60CBV/bookmananger/templates/book_list.html
{% extends 'abase.html' %}
{% block active %}
    <li class="active"><a href="/book_list/">书籍列表 <span class="sr-only">(current)</span></a></li>
    <li><a href="/publisher_list/">出版社列表 <span class="sr-only">(current)</span></a></li>
    <li><a href="/author_list/">作者列表 <span class="sr-only">(current)</span></a></li>
{% endblock %}
{% block zhuti %}
    <div class="panel-heading">书籍列表</div>
    <div class="panel-body">
        <a class="btn btn-primary btn-sm" href="/book_add/"> 添加 </a>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>序号</th>
                <th>ID</th>
                <th>书名</th>
                <th>作者</th>
                <th>出版社</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for book in all_books %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ book.pk }}</td>
                    <td>{{ book.title }}</td>
                    <td>
                        {% for author in book.author_set.all %}
                            {{ author.name }}
                        {% endfor %}
                    </td>
                    <td>{{ book.pub.name }}</td>
                    <td>
                        <a class="btn btn-danger btn-sm" href="/book_del/?pk={{ book.pk }}">删除</a>
                        <a class="btn btn-warning btn-sm" href="/book_edit/?pk={{ book.pk }}">编辑</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

第5阶段web框架之Django/day60CBV/bookmananger/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">图书管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

第5阶段web框架之Django/day60CBV/bookmananger/templates/publisher_add.html
{% extends 'abase.html' %}


{% block active %}
    <li><a href="/book_list/">书籍列表 <span class="sr-only">(current)</span></a></li>
    <li class="active"><a href="/publisher_list/">出版社列表 <span class="sr-only">(current)</span></a></li>
    <li><a href="/author_list/">作者列表 <span class="sr-only">(current)</span></a></li>
{% endblock %}


{% block zhuti %}
    <div class="panel-heading">添加出版社</div>
    <div class="panel-body">
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">出版社名称</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" id="inputEmail3" name="pub_name" value="{{ pub_name }}">
                    <p style="color: red">{{ error }}</p>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

第5阶段web框架之Django/day60CBV/bookmananger/templates/publisher_edit.html
{% extends 'abase.html' %}

{% block active %}
    <li><a href="/book_list/">书籍列表 <span class="sr-only">(current)</span></a></li>
    <li class="active"><a href="/publisher_list/">出版社列表 <span class="sr-only">(current)</span></a></li>
    <li><a href="/author_list/">作者列表 <span class="sr-only">(current)</span></a></li>

{% endblock %}
{% block zhuti %}
    <div class="panel-heading">编辑出版社</div>
    <div class="panel-body">
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-3 control-label">出版社名称</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" id="inputEmail3" name="pub_name"
                           value="{{ obj.name }}">
                    <p style="color: red">{{ error }}</p>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

第5阶段web框架之Django/day60CBV/bookmananger/templates/publisher_list.html
{% extends 'abase.html' %}

{% block active %}
    <li><a href="/book_list/">书籍列表 <span class="sr-only">(current)</span></a></li>
    <li class="active"><a href="/publisher_list/">出版社列表 <span class="sr-only">(current)</span></a></li>
    <li><a href="/author_list/">作者列表 <span class="sr-only">(current)</span></a></li>
{% endblock %}
{% block zhuti %}
    <div class="panel-heading">出版社列表</div>
    <div class="panel-body">
        <a class="btn btn-primary btn-sm" href="/publisher_add/"> 添加 </a>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>序号</th>
                <th>ID</th>
                <th>出版社名称</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for publisher in all_publishers %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ publisher.pk }}</td>
                    <td>{{ publisher }}</td>
                    <td>
                        <a class="btn btn-danger btn-sm" href="/publisher_del/?pk={{ publisher.pk }}">删除</a>
                        <a class="btn btn-warning btn-sm" href="/publisher_edit/?pk={{ publisher.pk }}">编辑</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}